<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Company;

class CompanySeeder extends Seeder
{
    public function run(): void
    {
        $companies = [
            [
                'name' => 'Amazon',
                'slug' => 'amazon',
                'tagline' => 'Global leader in e-commerce, cloud computing (AWS), digital streaming, and artificial intelligence.',
                'description' => 'Amazon is guided by four principles: customer obsession rather than competitor focus, passion for invention, commitment to operational excellence, and long-term thinking.',
                'industry' => 'Cloud Computing, E-Commerce, Artificial Intelligence',
                'type' => 'mnc',
                'website' => 'https://www.amazon.com',
                'linkedin_url' => 'https://www.linkedin.com/company/amazon',
                'founded_year' => 1994,
                'is_active' => true,
            ],
            [
                'name' => 'Google',
                'slug' => 'google',
                'tagline' => 'Organizing the world\'s information and making it universally accessible and useful through AI and Search.',
                'description' => 'Google is a multinational technology company focusing on artificial intelligence, search engine technology, cloud computing, computer software, and consumer electronics.',
                'industry' => 'Internet, Software, Artificial Intelligence',
                'type' => 'mnc',
                'website' => 'https://about.google',
                'linkedin_url' => 'https://www.linkedin.com/company/google',
                'founded_year' => 1998,
                'is_active' => true,
            ],
            [
                'name' => 'Microsoft',
                'slug' => 'microsoft',
                'tagline' => 'Empowering every person and every organization on the planet to achieve more with intelligent cloud & enterprise tools.',
                'description' => 'Microsoft enables digital transformation for the era of an intelligent cloud and an intelligent edge. Its mission is to empower every person and organization on the planet to achieve more.',
                'industry' => 'Software, Cloud Computing, Productivity',
                'type' => 'mnc',
                'website' => 'https://www.microsoft.com',
                'linkedin_url' => 'https://www.linkedin.com/company/microsoft',
                'founded_year' => 1975,
                'is_active' => true,
            ],
            [
                'name' => 'Apple',
                'slug' => 'apple',
                'tagline' => 'Designing world-class consumer electronics, software platforms, and digital services.',
                'description' => 'Apple revolutionizes personal technology with iPhone, iPad, Mac, Apple Watch, and Apple Vision Pro, alongside world-class software platforms like iOS and macOS.',
                'industry' => 'Consumer Electronics, Software, Cloud Services',
                'type' => 'mnc',
                'website' => 'https://www.apple.com',
                'linkedin_url' => 'https://www.linkedin.com/company/apple',
                'founded_year' => 1976,
                'is_active' => true,
            ],
            [
                'name' => 'Meta',
                'slug' => 'meta',
                'tagline' => 'Building technologies that help people connect, find communities, and grow businesses.',
                'description' => 'Meta builds technologies that help people connect, find communities, and grow businesses across Facebook, Instagram, WhatsApp, and the metaverse.',
                'industry' => 'Social Media, Virtual Reality, Artificial Intelligence',
                'type' => 'mnc',
                'website' => 'https://about.meta.com',
                'linkedin_url' => 'https://www.linkedin.com/company/meta',
                'founded_year' => 2004,
                'is_active' => true,
            ],
            [
                'name' => 'Netflix',
                'slug' => 'netflix',
                'tagline' => 'Entertaining the world with stories across genres and languages with streaming innovation.',
                'description' => 'Netflix is one of the world\'s leading entertainment services, offering TV series, documentaries, feature films, and games across a wide variety of genres and languages.',
                'industry' => 'Streaming, Entertainment, Cloud Architecture',
                'type' => 'mnc',
                'website' => 'https://www.netflix.com',
                'linkedin_url' => 'https://www.linkedin.com/company/netflix',
                'founded_year' => 1997,
                'is_active' => true,
            ],
            [
                'name' => 'Adobe',
                'slug' => 'adobe',
                'tagline' => 'Changing the world through digital experiences, creative media tools, and enterprise marketing clouds.',
                'description' => 'Adobe is the global leader in digital media and digital marketing solutions. Its creative, marketing, and document solutions empower everyone to bring digital creations to life.',
                'industry' => 'Creative Software, Digital Marketing, Cloud',
                'type' => 'mnc',
                'website' => 'https://www.adobe.com',
                'linkedin_url' => 'https://www.linkedin.com/company/adobe',
                'founded_year' => 1982,
                'is_active' => true,
            ],
            [
                'name' => 'Salesforce',
                'slug' => 'salesforce',
                'tagline' => 'The world\'s #1 AI CRM, connecting companies with their customers in a whole new way.',
                'description' => 'Salesforce powers Customer 360, uniting sales, service, marketing, and IT with built-in AI and automation across trusted cloud platforms.',
                'industry' => 'CRM, Enterprise Cloud, SaaS',
                'type' => 'mnc',
                'website' => 'https://www.salesforce.com',
                'linkedin_url' => 'https://www.linkedin.com/company/salesforce',
                'founded_year' => 1999,
                'is_active' => true,
            ],
            [
                'name' => 'Stripe',
                'slug' => 'stripe',
                'tagline' => 'Financial infrastructure for the internet — powering online payments, subscription billing, and global commerce.',
                'description' => 'Stripe builds economic infrastructure for the internet. Businesses of every size use our software to accept payments and manage their businesses online.',
                'industry' => 'Fintech, Financial Services, Payments',
                'type' => 'unicorn',
                'website' => 'https://stripe.com',
                'linkedin_url' => 'https://www.linkedin.com/company/stripe',
                'founded_year' => 2010,
                'is_active' => true,
            ],
            [
                'name' => 'Razorpay',
                'slug' => 'razorpay',
                'tagline' => 'Full-stack financial solutions enabling seamless payments, banking, and credit for digital businesses.',
                'description' => 'Razorpay is India\'s leading payments and banking platform for businesses, powering payments for millions of merchants with robust developer APIs.',
                'industry' => 'Fintech, Payments, Banking',
                'type' => 'unicorn',
                'website' => 'https://razorpay.com',
                'linkedin_url' => 'https://www.linkedin.com/company/razorpay',
                'founded_year' => 2014,
                'is_active' => true,
            ],
            [
                'name' => 'Zerodha',
                'slug' => 'zerodha',
                'tagline' => 'Pioneering discount retail brokerage in India through technology-first trading and investment platforms.',
                'description' => 'Zerodha is India\'s biggest stock broker offering low-cost brokerage and investment platforms including Kite, Coin, and Varsity.',
                'industry' => 'Fintech, Brokerage, Investment',
                'type' => 'unicorn',
                'website' => 'https://zerodha.com',
                'linkedin_url' => 'https://www.linkedin.com/company/zerodha',
                'founded_year' => 2010,
                'is_active' => true,
            ],
            [
                'name' => 'Swiggy',
                'slug' => 'swiggy',
                'tagline' => 'India\'s leading on-demand convenience platform delivering food, groceries, and essentials in minutes.',
                'description' => 'Swiggy is a pioneering on-demand convenience platform connecting consumers to thousands of restaurants, grocery stores, and local merchants across India.',
                'industry' => 'Food Delivery, Quick Commerce, Logistics',
                'type' => 'unicorn',
                'website' => 'https://www.swiggy.com',
                'linkedin_url' => 'https://www.linkedin.com/company/swiggy-in',
                'founded_year' => 2014,
                'is_active' => true,
            ],
            [
                'name' => 'Canva',
                'slug' => 'canva',
                'tagline' => 'Empowering the world to design anything and publish anywhere with intuitive visual design tools.',
                'description' => 'Canva is an online visual communications and collaboration platform with a mission to empower everyone in the world to design anything and publish anywhere.',
                'industry' => 'Design, SaaS, Productivity',
                'type' => 'unicorn',
                'website' => 'https://www.canva.com',
                'linkedin_url' => 'https://www.linkedin.com/company/canva',
                'founded_year' => 2013,
                'is_active' => true,
            ],
            [
                'name' => 'Notion',
                'slug' => 'notion',
                'tagline' => 'The connected workspace where better, faster work happens with notes, docs, and AI.',
                'description' => 'Notion is an all-in-one workspace that blends notes, tasks, wikis, and databases with collaborative AI tools for individuals and modern teams.',
                'industry' => 'Productivity, SaaS, Collaboration',
                'type' => 'unicorn',
                'website' => 'https://www.notion.so',
                'linkedin_url' => 'https://www.linkedin.com/company/notionhq',
                'founded_year' => 2013,
                'is_active' => true,
            ],
            [
                'name' => 'Postman',
                'slug' => 'postman',
                'tagline' => 'The world\'s leading API platform for building, designing, testing, and managing APIs.',
                'description' => 'Postman is an API platform used by over 30 million developers and 500,000 companies to simplify each step of the API lifecycle and streamline collaboration.',
                'industry' => 'Developer Tools, API Platform, SaaS',
                'type' => 'unicorn',
                'website' => 'https://www.postman.com',
                'linkedin_url' => 'https://www.linkedin.com/company/postman-platform',
                'founded_year' => 2014,
                'is_active' => true,
            ],
            [
                'name' => 'CRED',
                'slug' => 'cred',
                'tagline' => 'Rewarding financial discipline through high-trust community platforms and credit management.',
                'description' => 'CRED is a members-only club that rewards individuals for timely credit card bill payments while offering access to premium financial products.',
                'industry' => 'Fintech, Rewards, Financial Services',
                'type' => 'unicorn',
                'website' => 'https://cred.club',
                'linkedin_url' => 'https://www.linkedin.com/company/cred-club',
                'founded_year' => 2018,
                'is_active' => true,
            ],
            [
                'name' => 'Figma',
                'slug' => 'figma',
                'tagline' => 'Collaborative interface design tool connecting modern product teams from initial brainstorm to final code.',
                'description' => 'Figma is the leading collaborative design tool for teams building digital products, enabling seamless workflows between designers, developers, and product managers.',
                'industry' => 'Design, Collaboration, Developer Tools',
                'type' => 'startup',
                'website' => 'https://www.figma.com',
                'linkedin_url' => 'https://www.linkedin.com/company/figma',
                'founded_year' => 2012,
                'is_active' => true,
            ],
            [
                'name' => 'Vercel',
                'slug' => 'vercel',
                'tagline' => 'Develop, preview, ship — enabling developers to build faster, modern web applications globally.',
                'description' => 'Vercel provides developer tools and cloud infrastructure to build, deploy, and scale web applications, and is the creator of Next.js.',
                'industry' => 'Cloud Infrastructure, Web Frameworks, Developer Tools',
                'type' => 'startup',
                'website' => 'https://vercel.com',
                'linkedin_url' => 'https://www.linkedin.com/company/vercel',
                'founded_year' => 2015,
                'is_active' => true,
            ],
            [
                'name' => 'Supabase',
                'slug' => 'supabase',
                'tagline' => 'The open-source Firebase alternative providing Postgres, Auth, Realtime subscriptions, and Storage.',
                'description' => 'Supabase is an open source Firebase alternative. Build production-grade backends in a weekend with dedicated PostgreSQL databases and instant APIs.',
                'industry' => 'Database, Backend-as-a-Service, Open Source',
                'type' => 'startup',
                'website' => 'https://supabase.com',
                'linkedin_url' => 'https://www.linkedin.com/company/supabase',
                'founded_year' => 2020,
                'is_active' => true,
            ],
            [
                'name' => 'Linear',
                'slug' => 'linear',
                'tagline' => 'The issue tracker built for high-performance software teams who demand speed and craft.',
                'description' => 'Linear streamlines issues, sprints, and product roadmaps with unprecedented speed, keyboard shortcuts, and thoughtful design.',
                'industry' => 'Project Management, Issue Tracking, Software',
                'type' => 'startup',
                'website' => 'https://linear.app',
                'linkedin_url' => 'https://www.linkedin.com/company/linear-app',
                'founded_year' => 2019,
                'is_active' => true,
            ],
            [
                'name' => 'Perplexity AI',
                'slug' => 'perplexity-ai',
                'tagline' => 'AI conversational search engine providing accurate, cited answers in real time.',
                'description' => 'Perplexity AI unlocks the power of knowledge with an information discovery engine that delivers direct, up-to-date answers with cited sources.',
                'industry' => 'Artificial Intelligence, Search, NLP',
                'type' => 'startup',
                'website' => 'https://www.perplexity.ai',
                'linkedin_url' => 'https://www.linkedin.com/company/perplexity-ai',
                'founded_year' => 2022,
                'is_active' => true,
            ],
            [
                'name' => 'Resend',
                'slug' => 'resend',
                'tagline' => 'Email API for developers that makes sending transactional and marketing emails enjoyable.',
                'description' => 'Resend is the developer-first email platform that allows software teams to build, test, and deliver clean emails quickly with React Email components.',
                'industry' => 'Email Infrastructure, Developer Tools, SaaS',
                'type' => 'startup',
                'website' => 'https://resend.com',
                'linkedin_url' => 'https://www.linkedin.com/company/resend',
                'founded_year' => 2022,
                'is_active' => true,
            ],
            [
                'name' => 'Shopify',
                'slug' => 'shopify',
                'tagline' => 'The all-in-one global commerce platform empowering millions of businesses worldwide to sell anywhere.',
                'description' => 'Shopify provides trusted tools to start, grow, market, and manage a retail business of any size, making commerce better for everyone.',
                'industry' => 'E-Commerce, Software, SaaS',
                'type' => 'enterprise',
                'website' => 'https://www.shopify.com',
                'linkedin_url' => 'https://www.linkedin.com/company/shopify',
                'founded_year' => 2006,
                'is_active' => true,
            ],
            [
                'name' => 'Atlassian',
                'slug' => 'atlassian',
                'tagline' => 'Powering collaboration for agile teams worldwide with Jira, Confluence, Trello, and Bitbucket.',
                'description' => 'Atlassian creates software that helps teams organize, discuss, and complete shared work. Our products help teams of all sizes work better together.',
                'industry' => 'Team Collaboration, DevOps, Agile Software',
                'type' => 'enterprise',
                'website' => 'https://www.atlassian.com',
                'linkedin_url' => 'https://www.linkedin.com/company/atlassian',
                'founded_year' => 2002,
                'is_active' => true,
            ],
            [
                'name' => 'Datadog',
                'slug' => 'datadog',
                'tagline' => 'Essential monitoring and security platform for cloud applications and infrastructure.',
                'description' => 'Datadog is an observability service for cloud-scale applications, providing monitoring of servers, databases, tools, and services through a SaaS-based data analytics platform.',
                'industry' => 'Cloud Monitoring, Security, Observability',
                'type' => 'enterprise',
                'website' => 'https://www.datadoghq.com',
                'linkedin_url' => 'https://www.linkedin.com/company/datadog',
                'founded_year' => 2010,
                'is_active' => true,
            ],
            [
                'name' => 'Freshworks',
                'slug' => 'freshworks',
                'tagline' => 'Uncomplicating software with intuitive customer service, CRM, and IT service management.',
                'description' => 'Freshworks makes it fast and easy for businesses to delight their customers and employees with modern SaaS solutions that work out of the box.',
                'industry' => 'Customer Engagement, ITSM, SaaS',
                'type' => 'enterprise',
                'website' => 'https://www.freshworks.com',
                'linkedin_url' => 'https://www.linkedin.com/company/freshworks-inc',
                'founded_year' => 2010,
                'is_active' => true,
            ],
            [
                'name' => 'Tata Consultancy Services',
                'slug' => 'tcs',
                'tagline' => 'Global leader in IT services, consulting, and business solutions partner to the world\'s largest businesses.',
                'description' => 'TCS is an IT services, consulting and business solutions organization that has been partnering with many of the world’s largest businesses in their transformation journeys.',
                'industry' => 'IT Services, Consulting, Enterprise Solutions',
                'type' => 'indian_mnc',
                'website' => 'https://www.tcs.com',
                'linkedin_url' => 'https://www.linkedin.com/company/tata-consultancy-services',
                'founded_year' => 1968,
                'is_active' => true,
            ],
            [
                'name' => 'Infosys',
                'slug' => 'infosys',
                'tagline' => 'Global leader in next-generation digital services, cloud transformation, and consulting.',
                'description' => 'Infosys is a global leader in next-generation digital services and consulting, enabling clients in more than 50 countries to navigate their digital transformation.',
                'industry' => 'IT Services, Digital Transformation, Cloud',
                'type' => 'indian_mnc',
                'website' => 'https://www.infosys.com',
                'linkedin_url' => 'https://www.linkedin.com/company/infosys',
                'founded_year' => 1981,
                'is_active' => true,
            ],
            [
                'name' => 'Wipro',
                'slug' => 'wipro',
                'tagline' => 'Leading technology services and consulting company focused on building innovative solutions.',
                'description' => 'Wipro is a leading technology services and consulting company focused on building innovative solutions that address clients’ most complex digital transformation needs.',
                'industry' => 'IT Services, Technology Infrastructure, Consulting',
                'type' => 'indian_mnc',
                'website' => 'https://www.wipro.com',
                'linkedin_url' => 'https://www.linkedin.com/company/wipro',
                'founded_year' => 1945,
                'is_active' => true,
            ],
            [
                'name' => 'Zoho',
                'slug' => 'zoho',
                'tagline' => 'Unique and powerful software suite for entire businesses, built with long-term privacy focus.',
                'description' => 'Zoho offers a comprehensive suite of cloud applications covering CRM, finance, email, HR, and collaboration, trusted by over 100 million users globally.',
                'industry' => 'Business Software, SaaS, Cloud Productivity',
                'type' => 'indian_mnc',
                'website' => 'https://www.zoho.com',
                'linkedin_url' => 'https://www.linkedin.com/company/zoho',
                'founded_year' => 1996,
                'is_active' => true,
            ],
        ];

        foreach ($companies as $data) {
            Company::updateOrCreate(
                ['slug' => $data['slug']],
                $data
            );
        }
    }
}
