<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\PageSeo;

class SeoStaticPagesSeeder extends Seeder
{
    public function run()
    {
        $staticPages = [
            [
                'page_type' => 'static',
                'page_id' => null,
                'slug' => 'remote-jobs',
                'meta_title' => 'Remote Jobs - Work From Anywhere | Inaquired',
                'meta_description' => 'Find the best remote job opportunities from top companies. Work from anywhere with flexible remote positions in tech, marketing, design, and more.',
                'meta_keywords' => 'remote jobs, work from home, remote work, telecommute, flexible jobs, remote positions',
                'canonical_url' => url('/remote-jobs'),
                'og_title' => 'Remote Jobs - Work From Anywhere',
                'og_description' => 'Discover remote job opportunities from top companies worldwide.',
                'noindex' => false,
                'nofollow' => false,
            ],
            [
                'page_type' => 'static',
                'page_id' => null,
                'slug' => 'onsite-jobs',
                'meta_title' => 'Onsite Jobs - Office Based Positions | Inaquired',
                'meta_description' => 'Explore onsite job opportunities in offices across various locations. Find full-time office positions with leading companies.',
                'meta_keywords' => 'onsite jobs, office jobs, in-person work, full-time positions, office based careers',
                'canonical_url' => url('/onsite-jobs'),
                'og_title' => 'Onsite Jobs - Office Based Positions',
                'og_description' => 'Find onsite job opportunities in offices across various locations.',
                'noindex' => false,
                'nofollow' => false,
            ],
            [
                'page_type' => 'static',
                'page_id' => null,
                'slug' => 'hybrid-jobs',
                'meta_title' => 'Hybrid Jobs - Best of Both Worlds | Inaquired',
                'meta_description' => 'Find flexible hybrid job opportunities that combine remote work with office collaboration. Discover positions offering work-life balance.',
                'meta_keywords' => 'hybrid jobs, flexible work, hybrid remote, work from home office, flexible positions, hybrid work model',
                'canonical_url' => url('/hybrid-jobs'),
                'og_title' => 'Hybrid Jobs - Best of Both Worlds',
                'og_description' => 'Flexible hybrid positions combining remote work with office collaboration.',
                'noindex' => false,
                'nofollow' => false,
            ],
            [
                'page_type' => 'static',
                'page_id' => null,
                'slug' => 'internships',
                'meta_title' => 'Internships - Start Your Career Journey | Inaquired',
                'meta_description' => 'Discover internship opportunities to kickstart your career. Find paid internships in tech, business, design, and other fields.',
                'meta_keywords' => 'internships, student jobs, entry level, career start, paid internships, training programs',
                'canonical_url' => url('/internships'),
                'og_title' => 'Internships - Start Your Career Journey',
                'og_description' => 'Find internship opportunities to kickstart your professional career.',
                'noindex' => false,
                'nofollow' => false,
            ],
            [
                'page_type' => 'static',
                'page_id' => null,
                'slug' => 'companies',
                'meta_title' => 'Top Companies Hiring | Inaquired',
                'meta_description' => 'Browse top companies actively hiring talented professionals. Discover company profiles, culture, and available job opportunities.',
                'meta_keywords' => 'top companies, employers, company profiles, hiring companies, job opportunities',
                'canonical_url' => url('/companies'),
                'og_title' => 'Top Companies Hiring',
                'og_description' => 'Discover top companies and their available job opportunities.',
                'noindex' => false,
                'nofollow' => false,
            ],
            [
                'page_type' => 'static',
                'page_id' => null,
                'slug' => 'categories',
                'meta_title' => 'Job Categories - Find Jobs by Field | Inaquired',
                'meta_description' => 'Explore job opportunities by category. Find positions in technology, marketing, design, finance, healthcare, and many other fields.',
                'meta_keywords' => 'job categories, career fields, job types, industry jobs, professional categories',
                'canonical_url' => url('/categories'),
                'og_title' => 'Job Categories - Find Jobs by Field',
                'og_description' => 'Explore job opportunities across various professional categories.',
                'noindex' => false,
                'nofollow' => false,
            ],
            [
                'page_type' => 'static',
                'page_id' => null,
                'slug' => 'tools',
                'meta_title' => 'Career Tools & Resources | Inaquired',
                'meta_description' => 'Access free career tools and resources including resume builders, interview tips, salary calculators, and job search strategies.',
                'meta_keywords' => 'career tools, resume builder, interview tips, salary calculator, job search tools, career resources',
                'canonical_url' => url('/tools'),
                'og_title' => 'Career Tools & Resources',
                'og_description' => 'Free career tools and resources to boost your job search success.',
                'noindex' => false,
                'nofollow' => false,
            ],
            [
                'page_type' => 'static',
                'page_id' => null,
                'slug' => 'mnc-companies',
                'meta_title' => 'MNC Companies Jobs - Multinational Corporations | Inaquired',
                'meta_description' => 'Find job opportunities with top multinational corporations (MNCs). Explore careers with global companies offering excellent benefits and growth.',
                'meta_keywords' => 'MNC jobs, multinational companies, global corporations, international jobs, fortune 500 companies',
                'canonical_url' => url('/mnc-companies'),
                'og_title' => 'MNC Companies Jobs',
                'og_description' => 'Explore career opportunities with top multinational corporations.',
                'noindex' => false,
                'nofollow' => false,
            ],
            [
                'page_type' => 'static',
                'page_id' => null,
                'slug' => 'startup-companies',
                'meta_title' => 'Startup Jobs - Join Innovative Companies | Inaquired',
                'meta_description' => 'Discover exciting job opportunities with startup companies. Join innovative teams and be part of the next big thing in tech and business.',
                'meta_keywords' => 'startup jobs, startup careers, innovative companies, tech startups, entrepreneurial jobs',
                'canonical_url' => url('/startup-companies'),
                'og_title' => 'Startup Jobs - Join Innovative Companies',
                'og_description' => 'Find exciting opportunities with innovative startup companies.',
                'noindex' => false,
                'nofollow' => false,
            ],
            [
                'page_type' => 'static',
                'page_id' => null,
                'slug' => 'about',
                'meta_title' => 'About Inaquired - Your Career Partner',
                'meta_description' => 'Learn about Inaquired, the leading platform connecting talented professionals with job opportunities worldwide. Discover our mission and values.',
                'meta_keywords' => 'about inaquired, job platform, career hub, company mission, job portal',
                'canonical_url' => url('/about'),
                'og_title' => 'About Inaquired',
                'og_description' => 'Connecting talented professionals with opportunities worldwide.',
                'noindex' => false,
                'nofollow' => false,
            ],
            [
                'page_type' => 'static',
                'page_id' => null,
                'slug' => 'blog',
                'meta_title' => 'Career Tips & Job Search Insights | Inaquired Blog',
                'meta_description' => 'Discover expert career advice, job search tips, and professional development strategies. Stay updated with the latest trends in employment.',
                'meta_keywords' => 'career blog, job search advice, career development, professional tips, employment trends',
                'canonical_url' => url('/blog'),
                'og_title' => 'Inaquired Blog - Career & Job Search Insights',
                'og_description' => 'Expert career advice and job search tips for professional success.',
                'noindex' => false,
                'nofollow' => false,
            ],
            [
                'page_type' => 'static',
                'page_id' => null,
                'slug' => 'contact',
                'meta_title' => 'Contact Us - Inaquired Support',
                'meta_description' => 'Get in touch with Inaquired. We\'re here to help with your questions about job postings, partnerships, or platform support.',
                'meta_keywords' => 'contact inaquired, customer support, help, inquiries, job posting support',
                'canonical_url' => url('/contact'),
                'og_title' => 'Contact Inaquired',
                'og_description' => 'Get in touch with our team for support and inquiries.',
                'noindex' => false,
                'nofollow' => false,
            ],
            [
                'page_type' => 'static',
                'page_id' => null,
                'slug' => 'privacy',
                'meta_title' => 'Privacy Policy | Inaquired',
                'meta_description' => 'Read Inaquired\'s privacy policy to understand how we collect, use, and protect your personal information.',
                'meta_keywords' => 'privacy policy, data protection, user privacy, information security',
                'canonical_url' => url('/privacy'),
                'noindex' => false,
                'nofollow' => false,
            ],
            [
                'page_type' => 'static',
                'page_id' => null,
                'slug' => 'terms',
                'meta_title' => 'Terms of Service | Inaquired',
                'meta_description' => 'Review Inaquired\'s terms of service and user agreement for using our job platform.',
                'meta_keywords' => 'terms of service, user agreement, terms and conditions, platform rules',
                'canonical_url' => url('/terms'),
                'noindex' => false,
                'nofollow' => false,
            ],
            [
                'page_type' => 'static',
                'page_id' => null,
                'slug' => 'cookies',
                'meta_title' => 'Cookie Policy | Inaquired',
                'meta_description' => 'Learn about how Inaquired uses cookies to improve your browsing experience and platform functionality.',
                'meta_keywords' => 'cookie policy, cookies, website cookies, tracking, user experience',
                'canonical_url' => url('/cookies'),
                'noindex' => false,
                'nofollow' => false,
            ],
            [
                'page_type' => 'static',
                'page_id' => null,
                'slug' => 'testimonials',
                'meta_title' => 'Success Stories & Testimonials | Inaquired',
                'meta_description' => 'Read success stories and testimonials from professionals who found their dream jobs through Inaquired platform.',
                'meta_keywords' => 'testimonials, success stories, user reviews, job success, career achievements',
                'canonical_url' => url('/testimonials'),
                'noindex' => false,
                'nofollow' => false,
            ],
            [
                'page_type' => 'static',
                'page_id' => null,
                'slug' => 'support',
                'meta_title' => 'Help & Support | Inaquired',
                'meta_description' => 'Get help and support for using Inaquired platform. Find answers to common questions and contact our support team.',
                'meta_keywords' => 'help, support, FAQ, customer service, platform help, user guide',
                'canonical_url' => url('/support'),
                'noindex' => false,
                'nofollow' => false,
            ],
            [
                'page_type' => 'static',
                'page_id' => null,
                'slug' => 'advertise',
                'meta_title' => 'Advertise With Us | Inaquired',
                'meta_description' => 'Partner with Inaquired to reach talented professionals. Learn about our advertising opportunities and employer solutions.',
                'meta_keywords' => 'advertise, employer solutions, job posting, recruitment advertising, hiring partners',
                'canonical_url' => url('/advertise'),
                'noindex' => false,
                'nofollow' => false,
            ],
        ];

        foreach ($staticPages as $page) {
            PageSeo::updateOrCreate(
                ['slug' => $page['slug']],
                $page
            );
        }

        $this->command->info('Static page SEO entries created successfully!');
    }
}
